apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hello-deploy
spec:
  replicas: 5
  selector: 
    matchLabels:
      app: hello-world
  minReadySeconds: 10
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  
  template:
    metadata:
      labels: 
        app: hello-world
    spec:
     containers: 
     -  name: hell-pod
        image: nigelpoulton/k8sbook:1.0
        ports:
        - containerPort: 8080
        resources:
          limits: 
            cpu: "1500m"
            memory: "1000Mi"
        
      


    